### ISSUE TITLE
Extra space inside array brackets when dealing with some multi-line elements

### ISSUE THREAD

**Issue by rousskov** [Mark-Simulacrum/attractifier#11]
The following formatting change is undesirable:

``` diff
-let _CliOptions = [{
+let _CliOptions = [ {
     option: "help",
     type: "Boolean",
     overrideRequired: true,
     description: "show this help message",
-}];
+} ];
```

I suspect this change stems from the desire to pad array elements, but padding is harmful here. For consistency and simplicity sake, consider removing before/after padding in _all_ arrays:

``` diff
-let foo = [ bar, boo, baz ];
+let foo = [bar, boo, baz];
```

Attractifier does not pad function calls and possibly other "lists". Perhaps arrays do not need to be special?

**Comment by Mark-Simulacrum** [comment]
Fixed in 014fbd7abf627c7be898844c2cc88f1309e07899. The first case will now format with newlines after/before the array expression start, and the latter will no longer pad with spaces.

```js
let _CliOptions = [
    {
        option: "help",
        type: "Boolean",
        overrideRequired: true,
        description: "show this help message",
    }
];
```
