### ISSUE TITLE
Support for "async" and "await" keywords

### ISSUE THREAD

**Issue by eduard-bagdasaryan** [Mark-Simulacrum/attractifier#6]
I got several errors when running _uniform.sh_ on my script:

**1.**
`async function Test(take, callback) {`
`...`
`}` 
Error: In file "tests/test-squid-response-delay-pools.js": AssertionError: current value (async) is not equal to string (Test) at 44:0

**2.**
`await testCase.run();`
SyntaxError: In file "tests/test-squid-response-delay-pools.js": Unexpected token (95:14)

**3.**
`let resolver;`
`let promise = new Promise((resolve) => {`
`    resolver = resolve;`
`});`
Error: In file "tests/test-squid-response-delay-pools.js": AssertionError: current value (() is not equal to string (resolve) at 106:36

**Comment by Mark-Simulacrum** [comment]
I'm unable to reproduce with the latest version: What version of attractifier do you have installed?

`npm list -g attractifier` should give you the version of the installed package.

The latest version is 1.4.0; if that isn't the version you have, try running `npm update -g attractifier` to update.

**Comment by eduard-bagdasaryan** [comment]
Now I see the reason of my errors: I tried to use generator from the git source directory(as I did it some time ago), instead of installing it with `npm`. It is OK now.
Issue can be closed, thank you.
